apiVersion: v1
kind: Pod
metadata:
  name: hbma
  labels:
    dt: hdp
spec:
  hostname: hbma
  subdomain: hdp 
  containers:
  - name: hbma
    image: 120.96.143.74:8088/quay/dt210:latest
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
    command: [/bin/bash]
    volumeMounts:
     - name: dtconf
       mountPath: /opt/hadoop-2.10.1/etc/hadoop/
       subPath: hdp210
     - name: dtconf
       mountPath: /opt/hbase-1.4.13/conf/
       subPath: hbconf
     - name: dtconf
       mountPath: /opt/apache-zookeeper-3.6.2-bin/conf/
       subPath: zkconf
  volumes:
    - name: dtconf
      hostPath:
        path: /home/bigred/dt/conf
  dnsConfig:
    searches:
    - hdp.default.svc.dt.io
  nodeSelector:
    kubernetes.io/hostname : 120-96-143-82-k3m82
  restartPolicy: Never
