apiVersion: v1
kind: Pod
metadata:
  name: hs2
  labels:
    dt: hdp
spec:
  hostname: hs2
  subdomain: hdp 
  containers:
  - name: hs2
    image: 120.96.143.74:8088/quay/dt210:latest
    ports:
     - containerPort: 22
       hostPort: 10000
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
    volumeMounts:
     - name: dtconf
       mountPath: /opt/hadoop-2.10.1/etc/hadoop/
       subPath: hdp210
     - name: dtconf
       mountPath: /opt/apache-hive-3.1.2-bin/conf/
       subPath: hiveconf
     - mountPath: "/home/ybean"
       name: hs2
       subPath: ybean
     - mountPath: "/home/zbean"
       name: hs2
       subPath: zbean
    command: [/bin/bash]
    args: ["-c","useradd -m -s /bin/bash ybean;echo 'ybean:ybean' | chpasswd;useradd -m -s /bin/bash zbean;echo 'zbean:zbean' | chpasswd;/bin/bash"]
  volumes:
    - name: dtconf
      hostPath:
        path: /home/bigred/dt/conf
    - name: dtbin
      hostPath:
        path: /home/bigred/dt/bin
    - name: hs2
      hostPath:
        path: /opt/hs2
  dnsConfig:
    searches:
    - hdp.default.svc.dt.io
  nodeSelector:
    kubernetes.io/hostname : 120-96-143-82-k3m82
  restartPolicy: Never
