apiVersion: v1
kind: Pod
metadata:
  name: nna
  labels:
    dt: hdp
spec:
  hostname: nna
  subdomain: hdp 
  containers:
  - name: nna
    image: 120.96.143.74:8088/quay/dt210:latest
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true
    command: [/bin/bash]
    volumeMounts:
    - mountPath: "/home/bigred/nn"
      name: nn
    - mountPath: "/home/bigred/sn"
      name: sn
    - name: hdpconf
      mountPath: /opt/hadoop-2.10.1/etc/hadoop/
  volumes:
  - name: nn
    hostPath:
      path: /opt/nna/nn
  - name: sn
    hostPath:
      path: /opt/nna/sn
  - name: hdpconf
    hostPath:
      path: /home/bigred/dt/conf/hdp210
  dnsConfig:
    searches:
    - hdp.default.svc.dt.io
  nodeSelector:
    kubernetes.io/hostname : 120-96-143-81-k3m81
  restartPolicy: Never
