apiVersion: v1
kind: Pod
metadata:
  name: rma
  labels:
    dt: hdp
spec:
  hostname: rma
  subdomain: hdp 
  containers:
  - name: rma
    image: 120.96.143.74:8088/quay/dt210:latest
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true 
    volumeMounts:
     - name: hdpconf
       mountPath: /opt/hadoop-2.10.1/etc/hadoop/
     - name: spkconf
       mountPath: /opt/spark-3.0.1-bin-hadoop2.7/conf
    command: [/bin/bash]
  dnsConfig:
    searches:
    - hdp.default.svc.dt.io
  nodeSelector:
    kubernetes.io/hostname : 120-96-143-81-k3m81
  volumes:
    - name: hdpconf
      hostPath:
        path: /home/bigred/dt/conf/hdp210
    - name: spkconf
      hostPath:
        path: /home/bigred/dt/conf/spkconf
  restartPolicy: Never
