apiVersion: v1
kind: Pod
metadata:
  name: wka02
  labels:
    dt: hdp
spec:
  hostname: wka02
  subdomain: hdp 
  containers:
  - name: wka02
    image: 120.96.143.74:8088/quay/dt210:latest
    imagePullPolicy: IfNotPresent
    stdin: true
    tty: true 
    command: [/bin/bash]
    volumeMounts:
    - mountPath: "/home/bigred/dn"
      name: dn
    - name: dtconf
      mountPath: /opt/hadoop-2.10.1/etc/hadoop/
      subPath: hdp210
    - name: dtconf
      mountPath: /opt/spark-3.0.1-bin-hadoop2.7/conf
      subPath: spkconf
    - name: dtconf
      mountPath: /opt/hbase-1.4.13/conf/
      subPath: hbconf
  volumes:
  - name: dn
    hostPath:
      path: /opt/wka02/dn
  - name: dtconf
    hostPath:
      path: /home/bigred/dt/conf
  dnsConfig:
    searches:
    - hdp.default.svc.dt.io
  nodeSelector:
    kubernetes.io/hostname : 120-96-143-89-k3w89
  restartPolicy: Never
